name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your main branch if it's different

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.harsh1695 }}
        password: ${{ secrets.@Harsh1695}}

    - name: Build the Docker image
      run: |
        docker build -t harsh1695/my-portfolio:latest .

    - name: Push the Docker image
      run: |
        docker push harsh1695/my-portfolio:latest
